const AIProvider = require("./AIProvider");

class AnthropicProvider extends AIProvider {
  constructor({ apiKey, model }) {
    super();
    if (!apiKey) throw new Error("ANTHROPIC_API_KEY is not set");
    this.apiKey = apiKey;
    this.model = model || "claude-sonnet-4-6";
  }

  get name() {
    return "anthropic";
  }

  get supportsWebSearch() {
    return true;
  }

  async complete(system, messages, options = {}) {
    const body = {
      model: this.model,
      max_tokens: options.maxTokens || 1000,
      system,
      messages,
    };
    // Anthropic hosts this tool server-side — we don't implement the
    // search or the multi-turn loop ourselves, Anthropic does, and returns
    // the final answer with citations attached to the text that used them.
    if (options.enableWebSearch) {
      body.tools = [{ type: "web_search_20250305", name: "web_search", max_uses: 3 }];
    }

    const res = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.apiKey,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify(body),
      signal: options.signal,
    });

    if (!res.ok) {
      const errBody = await res.text().catch(() => "");
      const err = new Error(`Anthropic API error ${res.status}: ${errBody.slice(0, 300)}`);
      err.status = res.status;
      err.retryable = res.status === 429 || res.status >= 500;
      throw err;
    }

    const data = await res.json();
    const textBlocks = (data.content || []).filter((b) => b.type === "text");
    const text = textBlocks.map((b) => b.text).join("\n").trim();

    if (!options.enableWebSearch) return text;

    // Real citations only — pulled from what Anthropic's search actually
    // returned and attached to the text, never generated by asking the
    // model to "remember" a source.
    const citations = [];
    const seen = new Set();
    textBlocks.forEach((b) => {
      (b.citations || []).forEach((c) => {
        if (c.url && !seen.has(c.url)) {
          seen.add(c.url);
          citations.push({ url: c.url, title: c.title || c.url });
        }
      });
    });
    return { text, citations };
  }
}

module.exports = AnthropicProvider;
