import { Target, CheckCircle2, Flame, TrendingUp, Scale, ClipboardList } from "lucide-react";

export const STAGES = [
  "Idea", "Problem Validation", "Solution Validation", "MVP",
  "Early Customers", "Product-Market Fit", "Growth", "Scale",
  "Fundraising", "Expansion",
];

export const SKILL_LIST = [
  "Customer Discovery", "Sales", "Marketing", "Negotiation", "Hiring",
  "Leadership", "Product Thinking", "Finance", "Fundraising",
  "Networking", "Execution", "Strategic Thinking",
];

export const METRICS_FIELDS = [
  { key: "revenue", label: "Total Revenue", info: "Total money collected from customers before any costs are subtracted." },
  { key: "mrr", label: "MRR", info: "Monthly Recurring Revenue — predictable subscription revenue you collect every month." },
  { key: "arr", label: "ARR", info: "Annual Recurring Revenue — your MRR × 12; predictable yearly revenue from subscriptions." },
  { key: "grossProfit", label: "Gross Profit", info: "Revenue minus the direct cost of delivering your product or service (COGS)." },
  { key: "netProfit", label: "Net Profit", info: "What's left after ALL expenses — COGS, salaries, rent, marketing, everything — are subtracted from revenue." },
  { key: "users", label: "Total Users", info: "Everyone who has signed up or uses your product, whether they pay or not." },
  { key: "payingCustomers", label: "Paying Customers", info: "The number of customers currently paying you money." },
  { key: "retention", label: "Retention %", info: "The share of customers who are still active or paying after a given period." },
  { key: "churn", label: "Churn %", info: "The share of customers who stopped paying or left in a given period — the inverse of retention." },
  { key: "cac", label: "CAC", info: "Customer Acquisition Cost — total sales & marketing spend divided by new customers acquired." },
  { key: "ltv", label: "LTV", info: "Lifetime Value — total revenue you expect from a customer over your entire relationship with them." },
  { key: "burnRate", label: "Monthly Burn Rate", info: "How much cash you're spending each month beyond what you earn." },
  { key: "runway", label: "Runway (months)", info: "How many months you can keep operating before running out of cash at your current burn rate." },
];

export const HEALTH_CATEGORIES = [
  "Product", "Growth", "Sales", "Revenue", "Customer Satisfaction",
  "Retention", "Execution", "Financial Health", "Team", "Founder Wellbeing",
];

export const WEEKLY_QUESTIONS = [
  { key: "achievement", label: "Biggest achievement this week?" },
  { key: "mistake", label: "Biggest mistake this week?" },
  { key: "lesson", label: "Biggest lesson learned?" },
  { key: "blocker", label: "Biggest blocker right now?" },
  { key: "risk", label: "Biggest risk you're watching?" },
  { key: "customerInsight", label: "Most important customer insight this week?" },
  { key: "revenueUpdate", label: "Revenue update — what changed?" },
  { key: "productUpdate", label: "Product progress this week?" },
  { key: "teamUpdate", label: "Team update, even if it's just you?" },
  { key: "energy", label: "Mental energy this week, 1–10?" },
];

export const BADGES = [
  { key: "firstMission", label: "First Mission", icon: Target, test: (d) => (d.missionsCompleted || 0) >= 1 },
  { key: "fiveMissions", label: "5 Missions", icon: CheckCircle2, test: (d) => (d.missionsCompleted || 0) >= 5 },
  { key: "streak7", label: "7-Day Streak", icon: Flame, test: (d) => (d.streak || 0) >= 7 },
  { key: "streak30", label: "30-Day Streak", icon: Flame, test: (d) => (d.streak || 0) >= 30 },
  { key: "metricsTracked", label: "Metrics Tracked", icon: TrendingUp, test: (d) => d.hasMetrics },
  { key: "firstDecision", label: "First Decision", icon: Scale, test: (d) => (d.decisionsCount || 0) >= 1 },
  { key: "firstReview", label: "First Weekly Review", icon: ClipboardList, test: (d) => (d.reviewsCount || 0) >= 1 },
];

export const TERMS_INTRO = "Founder Companion is an educational and productivity tool, not a substitute for professional advice.";
export const TERMS_BODY = [
  "All missions, coaching, skill assessments, metric read-outs, and mentor chat responses are generated by an AI model and are provided for general informational and educational purposes only.",
  "AI-generated guidance can be incomplete, outdated, or factually incorrect. It does not constitute legal, financial, tax, accounting, investment, medical, psychological, or professional business advice, and no advisor-client or fiduciary relationship is created by using this app.",
  "You are solely responsible for evaluating and verifying any recommendation before acting on it, and for the outcomes of decisions made about your business, finances, hiring, fundraising, or personal wellbeing. Consult qualified professionals — lawyers, accountants, licensed financial advisors, or mental health professionals — for decisions that carry real risk.",
  "To the fullest extent permitted by law, the makers of this app disclaim all liability for any loss, damage, or business outcome — direct or indirect — arising from reliance on content generated within the app, including missions, metrics interpretations, skill assessments, and chat responses.",
  "This app now sends data to a backend server you control to generate AI responses. Review your own backend's data handling before relying on it for sensitive information.",
];

export const QUESTIONS = [
  { key: "founderName", label: "First, what should I call you?", placeholder: "Your name" },
  { key: "background", label: "Tell me your background — school, jobs, anything technical, sales, or business you've done. No polishing, just the facts.", placeholder: "e.g. Mechanical engineer, worked at a factory for 3 years, never ran a business before" },
  { key: "whyStarting", label: "Why are you starting a company? What's pulling you into this?", placeholder: "Your honest reason" },
  { key: "startupName", label: "What's the startup called, and in one line, what does it do?", placeholder: "Name — what it does" },
  { key: "stage", label: "Where are you right now — idea only, talking to customers, built something, or already have paying users?", placeholder: "Describe honestly" },
  { key: "biggestChallenge", label: "What's the single hardest thing you're stuck on this week?", placeholder: "Be specific" },
  { key: "confidence", label: "Where do you feel weakest — sales, product, hiring, finance, something else?", placeholder: "Your honest weak spot" },
];

export const FAQS = [
  {
    q: "Is the mentor's advice guaranteed to be correct?",
    a: "No. Responses are generated by an AI model and can be incomplete, outdated, or simply wrong. Treat every mission, metric read, and piece of advice as a starting hypothesis to test, not a verdict.",
  },
  {
    q: "Should I make real business or financial decisions based on this app alone?",
    a: "No. Validate anything consequential — legal, financial, hiring, fundraising — with a qualified professional and your own judgment before acting.",
  },
  {
    q: "Where does my data go now?",
    a: "Your profile, missions, and chat history stay on this device. AI requests go to your own backend server, which calls your chosen AI provider using a key that never touches this app's frontend code.",
  },
  {
    q: "How do I reset my profile?",
    a: "There's no in-app reset button yet — mention it in feedback below and it'll be prioritized.",
  },
  {
    q: "What do I do if a mission feels wrong for my stage?",
    a: "Rate it down using the thumbs-down on the Mission tab and tell us why — that's fed directly into how future missions are generated.",
  },
];

export const todayStr = () => new Date().toISOString().slice(0, 10);
